apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm.fullname" . }}-namespaced
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: leader election support
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]

  # Application: Custom resources managed by this operator in the namespace
  - apiGroups: [ops.veitosiander.de]
    resources:
      - litellmkeys
      - litellmmodels
      - ollamamodels
      - n8napikeys
      - n8nadminusers
      - openwebuibanners
      - openwebuichannels
      - openwebuigroups
      - openwebuiprompts
      - openwebuitoolservers
    verbs: [list, watch, get, create, update, patch, delete]

  # Application: Secrets management for n8n_api_key operator
  # This operator creates Kubernetes secrets containing N8N API keys
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
