{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-key-requestor.fullname" . }}-backend-config
  labels:
    {{- include "llm-key-requestor.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  config.yaml: |
    {{- toYaml .Values.backend.config | nindent 4 }}
{{- end }}
