{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "llm-key-requestor.fullname" . }}
  labels:
    {{- include "llm-key-requestor.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
