{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-key-requestor.fullname" . }}-frontend
  labels:
    {{- include "llm-key-requestor.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-key-requestor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
