{{- if .Values.admin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-key-requestor.fullname" . }}-admin
  labels:
    {{- include "llm-key-requestor.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-key-requestor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
{{- end }}
