{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-key-requestor.fullname" . }}-backend
  labels:
    {{- include "llm-key-requestor.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-key-requestor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
